### ISSUE TITLE
Lab Module 6 moving router to infra node shows empty spec

### ISSUE THREAD

**Issue by steven-ellis** [openshift/openshift-cns-testdrive#454]
Currently the LAB shows that the response to
`
oc get ingresscontrollers.operator.openshift.io default -n openshift-ingress-operator -o yaml
`

includes
```
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
```
The currently lab deployment shows an empty spec.
```
spec: {}                                                                                                       
```
