### ISSUE TITLE
Mod 8 Use cephrbd volumes for elasticsearch storage

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#495]
Right now this module, OpenShift Log Aggregation, has a statement that PVC/PV are created using the default storageclass gp2. This does not happen.

```
You will also see the storage for ElasticSearch being automatically provisioned from the default storage service if you query the PersistentVolumeClaim objects in this project
```
Even so it would be best that the storage was created using the cephrbd storageclass as shown below. This was tested and works as expected.

```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 3
      storage:
         storageClassName: ocs-storagecluster-ceph-rbd
         size: 100Gi
      redundancyPolicy: "SingleRedundancy"
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        request:
          memory: 4G
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/infra: ""
  curation:
    type: "curator"
    curator:
      schedule: "30 3 * * *"
      nodeSelector:
        node-role.kubernetes.io/infra: ""
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
```
$ oc get pods,pvc -n openshift-logging
```
NAME                                                READY   STATUS    RESTARTS   AGE
pod/cluster-logging-operator-cb4dd8688-lx428        1/1     Running   0          13m
pod/elasticsearch-cdm-hrae1a3q-1-85d8b594d5-b5v9g   2/2     Running   0          7m52s
pod/elasticsearch-cdm-hrae1a3q-2-75648cb985-bvtqp   2/2     Running   0          7m48s
pod/elasticsearch-cdm-hrae1a3q-3-5fb464b8df-tx8g2   2/2     Running   0          7m43s
pod/fluentd-68wks                                   1/1     Running   0          7m50s
pod/fluentd-8zk5b                                   1/1     Running   0          7m50s
pod/fluentd-b7q45                                   1/1     Running   0          7m50s
pod/fluentd-bljrw                                   1/1     Running   0          7m50s
pod/fluentd-cfvl6                                   1/1     Running   0          7m50s
pod/fluentd-d9nhb                                   1/1     Running   0          7m50s
pod/fluentd-fszpn                                   1/1     Running   0          7m50s
pod/fluentd-gxrqg                                   1/1     Running   0          7m50s
pod/fluentd-hspj6                                   1/1     Running   0          7m50s
pod/fluentd-m62fc                                   1/1     Running   0          7m50s
pod/fluentd-qzxhz                                   1/1     Running   0          7m50s
pod/fluentd-rrz66                                   1/1     Running   0          7m50s
pod/fluentd-tkzck                                   1/1     Running   0          7m50s
pod/fluentd-vlkgb                                   1/1     Running   0          7m50s
pod/fluentd-xgg7v                                   1/1     Running   0          7m50s
pod/kibana-5c5b6ff7f7-jfbmn                         2/2     Running   0          7m52s

NAME                                                               STATUS   VOLUME
                   CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
persistentvolumeclaim/elasticsearch-elasticsearch-cdm-hrae1a3q-1   Bound    pvc-f3d3b797-37fc-11ea-9
e4c-0a75d5915b96   94Gi       RWO            ocs-storagecluster-ceph-rbd   7m52s
persistentvolumeclaim/elasticsearch-elasticsearch-cdm-hrae1a3q-2   Bound    pvc-f3d5bcaa-37fc-11ea-9
e4c-0a75d5915b96   94Gi       RWO            ocs-storagecluster-ceph-rbd   7m52s
persistentvolumeclaim/elasticsearch-elasticsearch-cdm-hrae1a3q-3   Bound    pvc-f3d93244-37fc-11ea-9
e4c-0a75d5915b96   94Gi       RWO            ocs-storagecluster-ceph-rbd   7m52s
```
